Add HireFire to account list
voiio/voiio.github.io pull request #10
Opened 2022-04-01 09:50 UTC by codingjoe

2022-04-01 12:31 UTC, fidelitas requested changes
Proposed some improvements.

2022-04-01 12:31 UTC, fidelitas commented on accounts.md
> +Only after completing both step can you be added to our HireFire organization.
```suggestion
We use [HireFire][hirefire] in combination with Heroku for load based auto-scaling.
Please, setup an account with your voiio E-Mail address and enable "2FA".
Only after completing both steps, we can add you to our "HireFire"-organization. Please refer to your team lead for adding you to the organization.

[hirefire]: https://hirefire.io/
```

2022-04-04 07:43 UTC, merged

2022-04-04 07:48 UTC, codingjoe commented
Thx @fidelitas 
FYI, we usually reserve `request changes` reviews, if we want to halt deployment or veto a change. For anything else, we use comments or approve with comments for optional improvements. GitHub has done a poor job with the UI here, and change requests can come on strong or discouraging. Comments have yielded more constructive discussions for us in the past.

2022-04-04 08:00 UTC, fidelitas commented
@codingjoe thanks for letting me know.
Do you want me to do anything for this PR for now?

2022-04-04 08:00 UTC, fidelitas commented
Oh. It's merged. Never mind.

2022-04-04 08:19 UTC, codingjoe commented
No, but you should get a hirefire account and added to our org, so you can disable or change it, if need be.